using System;
using System.Web;

namespace RequestFlow.Infrastructure
{
    /// <summary>
    /// 
    /// </summary>
    public class InfoHandler : IHttpHandler
    {
        /// <summary>
        /// Enables processing of HTTP Web requests by a custom HttpHandler that
        /// implements the <see cref="T:System.Web.IHttpHandler" /> interface.
        /// </summary>
        /// <param name="app">An <see cref="T:System.Web.HttpContext" /> object that provides
        /// references to the intrinsic server objects (for example, Request, Response, Session,
        /// and Server) used to service HTTP requests.</param>
        public void ProcessRequest(HttpContext context)
        {
            if (context.Request.RawUrl == "/Test/Index")
            {
                context.Server.TransferRequest("/Home/Index");
            }
            else
            {
                context.Response.Write("Content generated by InfoHandler");
            }
        }

        /// <summary>
        /// Gets a value indicating whether another request can use the <see cref="T:System.Web.IHttpHandler" />
        /// instance.
        /// </summary>
        /// <returns>true if the <see cref="T:System.Web.IHttpHandler" /> instance is reusable;
        /// otherwise, false.</returns>
        /// <value></value>
        public bool IsReusable
        {
            get
            {
                return false;
            }
        }
    }
}